#ifndef UTIL_H
#define UTIL_H

#include <cstdint>

enum class MoveType {
  REGULAR_KING_MOVE,
  LONG_CASTLE_KING_MOVE,
  SHORT_CASTLE_KING_MOVE,
  QUEEN_MOVE,
  ROOK_MOVE,
  BISHOP_MOVE,
  KNIGHT_MOVE,
  REGULAR_PAWN_CAPTURE,
  EN_PASSANT_PAWN_CAPTURE,
  PAWN_MOVE,
  PAWN_MOVE_TWO_SQUARES,
  PAWN_PROMOTE_QUEEN,
  PAWN_PROMOTE_ROOK,
  PAWN_PROMOTE_BISHOP,
  PAWN_PROMOTE_KNIGHT,
};

enum Pieces : int8_t {
  KING = 0,
  QUEEN = 1,
  ROOK = 2,
  BISHOP = 3,
  KNIGHT = 4,
  PAWN = 5,
  EMPTY = 6,
};
#endif // !UTIL_H
